name = "Pion"
author = "Dani"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a8b73e9bb192c345d462cbe03eedbe1f8a0ffdc09dd153cb6d52147f52a51ec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
