name = "Pion"
author = "Dani"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbe3a763b3618e59cee025de6211c705ae6d5651cf8b0b0887af97ce2e62fec4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
