name = "Pion"
author = "Dani"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd91079aa692e742668b1c13df16e80baaf78ea668f2bb4d057b956baea9f5a5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
